version: "3.8"
services:
    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user123
            POSTGRES_DB: db